server {
    listen       80;
    server_name  roz.yeetorskeet.com;

    location / {
        return 301 https://$host$request_uri;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name roz.yeetorskeet.com;

    ssl_certificate /etc/letsencrypt/live/roz.yeetorskeet.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/roz.yeetorskeet.com/privkey.pem;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_pass http://django-app:8000/;
        proxy_ssl_session_reuse off;
        proxy_set_header Host $http_host;
        proxy_pass_header Server;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
    }
}