FROM node:20-slim AS build

ARG VITE_MODE

WORKDIR ./frontend

COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend ./
RUN npx vite build --mode $VITE_MODE

FROM nginx:alpine
COPY --from=build /frontend/dist ./frontend/dist/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
