services:
  app:
    build:
      context: .
      args:
        VITE_MODE: production
    container_name: django-app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB=${DJANGO_DB:-default}
    volumes:
      - ./roz_loot_tracker/db.sqlite3:/roz_loot_tracker/db.sqlite3
  nginx:
    container_name: nginx-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_MODE: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/zekraidtools.com:/etc/letsencrypt/live/zekraidtools.com
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
    depends_on:
      - app