server {
    listen 80 default_server;
    server_name _;

    location /api/ {
        proxy_pass http://app:8000;
    }

    location /static/ {
        alias /frontend/dist/;
    }

    location / {
        try_files $uri $uri/ /static/index.html;
    }
}