services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/roz.yeetorskeet.com:/etc/letsencrypt/live/roz.yeetorskeet.com
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive