# Generated by Django 5.2.7 on 2025-11-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_approveraidattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApproveRaidAttendance',
            new_name='RaidAttendanceApproval',
        ),
    ]
