# Generated by Django 5.2.7 on 2025-11-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_approveraidattendance_raidattendanceapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidattendanceapproval',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
