# Generated by Django 5.2.7 on 2025-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_raidattendanceapproval_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidattendanceapproval',
            name='raid_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
