# Generated by Django 5.2.7 on 2025-12-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_raidattendanceapproval_raid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemawarded',
            name='alt_loot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemawarded',
            name='magelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemawarded',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
