# Generated by Django 5.2.7 on 2026-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_itemawarded_alt_loot_itemawarded_magelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
