# Generated by Django 5.2.7 on 2026-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
