# Generated by Django 5.2.7 on 2026-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemawarded',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('alt', 'Alt'), ('preferred', 'Preferred'), ('main_magelo', 'Main Magelo'), ('preferred_magelo', 'Preferred Magelo'), ('alt_magelo', 'Alt Magelo')], default='main', max_length=30),
        ),
    ]
