# Generated by Django 5.2.7 on 2026-08-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_itemawarded_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemawarded',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('alt', 'Alt'), ('preferred', 'Preferred'), ('main_magelo', 'Main Magelo'), ('preferred_magelo', 'Preferred Magelo'), ('alt_magelo', 'Alt Magelo'), ('main_alt', 'Main Alt')], default='main', max_length=30),
        ),
    ]
