# Generated by Django 5.2.7 on 2026-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_itemawarded_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='character',
            name='unique_main_per_player',
        ),
        migrations.RemoveConstraint(
            model_name='character',
            name='unique_main_alt_per_player',
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('MAIN', 'Main'), ('MAIN_ALT', 'Main Alt'), ('ALT', 'Alt')], default='ALT', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'MAIN')), fields=('player',), name='unique_main_per_player'),
        ),
    ]
