# Generated by Django 5.2.7 on 2026-08-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_character_unique_main_per_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tier',
            field=models.CharField(blank=True, choices=[('QUARM', 'Quarm'), ('TIME', 'Time'), ('ELEMENTAL', 'Elemental'), ('PRE-ELEMENTAL', 'Pre-Elemental')], max_length=20, null=True),
        ),
    ]
