# Generated by Django 5.2.7 on 2026-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
