from django.core.management.base import BaseCommand
from django.db import transaction

from app import models

DISCORD_ID_MAP = {
    "titanuk": "Titanuk",
    "silikten": "Silikten",
    "chestrockwell3419": "Big G",
    "saltycrackers": "Salty",
    "thors8694": "Mcoy",
    "balutlv": "Gream",
    "pok1858": "Pok",
    "grixus.": "Grixus",
    "hurl_": "Hurl",
    "goblin6644#0": "Last Boss",
    "noni3115": "Noni",
    "shinaba": "Shinaba",
    "shody123": "Shody",
    "ungh": "Ungh",
    "lethdar": "Lethdar",
    "baronjune": "baronjune",
    "fatalwan": "Fatalwan",
    "keep__": "Keep",
    "nuke9859": "Nuke",
    "willan": "Willan",
    "kano4861": "Kano",
    "ksah": "Ksah",
    "blueflower9": "Blueflower",
    "cythix.ip": "Kugaz",
    "koidokenmachete": "Machete",
    "cybercop": "Cybercop",
    "plag5944": "Sars",
    "noidia": "Noidz",
    "nba4400": "Nba",
    ".firenz": "Firenz",
    "mortii2940": "Mortii",
    "nocsucow": "Nocsucow",
    "malagen": "Malagen",
    "knife8187": "Knife",
    "charming2340": "Charming",
    "lucidnpc": "Genedin",
    "rukmok": "Rukmok",
    "vaporize1334": "Vaporise",
    "reptoid_sol": "Reptoid",
    "frodo4827": "Frodo",
    "metroyd.": "Metroyd",
    "deimos888": "Deimos",
    "strut": "Strut",
    "hazelnut0339": "Hazelnut",
    "in_spir_e": "Inspire",
    ".vantaris": "Violence",
    "krunchh.": "Krunchh",
    "bodied3": "Bodied",
    "birdop": "Birdop",
    "_sharknado": "Sharknado",
    "pnboots": "Boomwiz",
    "delune": "Delune",
    "tranch1144": "Tranch",
    "akp3533": "Kap",
    "nuke4265": "Wisecrak",
    "hagard_69334": "Hagard",
    "skitter5007": "Skitter",
    "beihr": "Beihr",
    "boat6918": "boat",
    "darkhorn.": "darkhorn",
    "little8858": "Little",
    "nerfed1": "Nerfed",
    "kringe1060": "Kringe",
    "smooth7398": "Taquisha",
    "haydnt.": "Brobb",
    "godhandgu": "Tune",
    "ticeshotit": "Slimelord",
    "cornisthebest": "Mendl",
    ".faldorf": "Faldorf",
    "_visible": "Visible",
    "hyjal_": "Acarer",
    "biglimey": "Biglime",
    "lizard_eq99": "Shakirra",
    "goatassin": "Goatassin",
    "warlockezorn": "Zorn/Demonstab",
    "vanco_lash": "Vanco",
    "billieboyo": "Sangre",
    "durant2323": "Iovvdovvn",
    "producer": "Producer",
    "schnnow": "Jokong/Jessie",
    "aseplanker": "Azzar",
    "moochie.kitty": "Ninja",
    "uaeb": "Uaeb",
    "shivalry3pt": "Threepeat",
    "caldwillis": "Herban",
    "mochadrone1975": "Exam",
    "awakening6572": "Taeter",
    "lazzarus1969": "Herbsaint",
    "skeeter_": "Skeeter",
    "aygok": "Aygok",
    "o.g._mobbs": "Mandelgar",
    "rawbinurhood": "Rawbin",
    "jefu4791": "Jefu",
    "boogs1332": "Ohhso",
    "re.ef": "Reef",
    "kajoo": "Kajoo",
    "bigr_": "Ajax",
    "pdunny": "Bannin",
    "namji": "Partymike",
    "poopypants5181": "Reon",
    "amberr08053": "Amberr",
    "strikkerr": "Strikerr",
    "jore9716": "Ranjore",
    ".thievin": "Gram",
    "ginlok": "Rickjames",
    "c_rip": "Crip",
    ".choopa": "Choopy",
    "flexinbrah": "Crown",
    "didymuser": "Digital",
    "your_mortgage_broker": "Dirtyy",
    "grokmol": "Dustmop",
    "sholistic": "Fictive",
    "filpox.": "Filpox",
    "godzfury": "Godsfury// Wrecked",
    "greyn0291": "Greyn",
    "zuljah_": "Jah",
    "juicee5076": "Jewcy",
    "bh209": "Kilbur",
    "kilkur": "Kilkur",
    "gregpaso": "Klep",
    "tigermaw": "Kodo",
    "lesly76844": "Lesly",
    "maxisthefoat": "Maxisthefoat",
    "slaughterwall": "Meztup",
    "respin121": "Ogor",
    "quiex_vz": "Quiexvz",
    "heartfelt_relic": "Relic",
    "retticus": "Retticus",
    "itzgambit.": "Revy",
    "baggy04": "Roger",
    "sraalok": "Sraalok",
    "_stryne_": "Stryne",
    "supereagle2": "Superbeagle",
    "volture8307": "Volture",
    "voodoonasty": "Voodoonasty",
    "yulath": "Yulath",
    "plehzur": "Mali",
    "brobbenlive": "Brobben",
    "aprilthenarf": "Apes",
    "afflictx": "Afflictx",
}


class Command(BaseCommand):
    help = "create a raid attendance row"
    with transaction.atomic():

        def handle(self, *args, **options):
            for discord_id, player_name in DISCORD_ID_MAP.items():
                try:
                    player_to_title = player_name.title()
                    player = models.Player.objects.get(name=player_to_title)
                    player.discord_id = discord_id
                    player.save()
                except models.Player.DoesNotExist:
                    return self.stdout.write(self.style.ERROR(f"Player with name {player_name} does not exist."))
            return self.stdout.write(self.style.SUCCESS("Successfully backfilled discord ids for Player's"))
